name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build (React Router v7)
        run: npm run build

      # 必须：配置 Pages（官方动作）
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 探测输出目录（RR v7 默认为 build/client；Vite 为 dist）
      - name: Detect output dir
        id: out
        run: |
          if [ -d "build/client" ]; then
            echo "dir=build/client" >> $GITHUB_OUTPUT
          else
            echo "dir=dist" >> $GITHUB_OUTPUT
          fi

      # 打印产物，确认是否有 assets/*.js/*.css
      - name: List output dir
        run: |
          echo "OUTPUT = ${{ steps.out.outputs.dir }}"
          ls -la "${{ steps.out.outputs.dir }}"
          echo "---- files (depth 2) ----"
          find "${{ steps.out.outputs.dir }}" -maxdepth 2 -type f -print

      # SPA 刷新回退
      - name: Create 404.html for SPA fallback
        run: |
          cp "${{ steps.out.outputs.dir }}/index.html" "${{ steps.out.outputs.dir }}/404.html" || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.out.outputs.dir }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
