name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build (React Router)
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 检测输出目录：RR(v7)=build/client；Vite=dist
      - name: Detect output dir
        id: out
        run: |
          if [ -f "build/client/index.html" ]; then
            echo "dir=build/client" >> $GITHUB_OUTPUT
          elif [ -f "dist/index.html" ]; then
            echo "dir=dist" >> $GITHUB_OUTPUT
          else
            echo "No index.html found in build/client or dist"
            echo "==== ls -la ===="
            ls -la
            echo "==== find build (depth 3) ===="
            [ -d build ] && find build -maxdepth 3 -type f -print || true
            echo "==== find dist (depth 3) ===="
            [ -d dist ] && find dist -maxdepth 3 -type f -print || true
            exit 1
          fi

      - name: Verify output
        run: |
          echo "OUTPUT = ${{ steps.out.outputs.dir }}"
          test -f "${{ steps.out.outputs.dir }}/index.html"
          find "${{ steps.out.outputs.dir }}" -maxdepth 2 -type f -print

      # SPA 刷新回退
      - name: Create 404.html for SPA fallback
        run: cp "${{ steps.out.outputs.dir }}/index.html" "${{ steps.out.outputs.dir }}/404.html"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.out.outputs.dir }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
